name: Build macOS App

on:
  push:
    branches: [main, beta]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pyinstaller svgwrite

      - name: Build with PyInstaller
        run: pyinstaller --noconsole --onefile --name "StohrerPadGenerator" main.py

      - name: Upload macOS App
        uses: actions/upload-artifact@v4
        with:
          name: StohrerPadGenerator-macOS
          path: dist/StohrerPadGenerator
