name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pyinstaller svgwrite

    - name: Build with PyInstaller
      run: pyinstaller --noconsole --onefile --name "StohrerPadGenerator" main.py

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: StohrerPadGenerator
        path: dist/StohrerPadGenerator.exe
